name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build application
      run: |
        # Replace this command with your build command
        python build.py

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy application
      run: ./
        python deploy.py

  generate-artifacts:
    name: Generate Artifacts
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: path/to/artifacts
