name: Bellman-Ford CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run static analysis
      run: |
        flake8 .

    - name: Run script
      run: |
        python main.py

    - name: Generate artifacts
      run: |
        echo "Generating artifacts for Linux build"
        mkdir -p artifacts
        cp *.py artifacts/
      continue-on-error: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-artifacts
        path: artifacts/

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run static analysis
      run: |
        flake8 .

    - name: Run script
      run: |
        python main.py

    - name: Generate artifacts
      run: |
        echo "Generating artifacts for Windows build"
        mkdir artifacts
        copy *.py artifacts
      continue-on-error: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifacts
        path: artifacts/
